export const sheltonEquipmentRows = [
  {
    "id": 1,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 1,
    "processName": "Water Supply",
    "equipmentGroup": "5HP HYDRP PUMP",
    "equipmentName": "5HP HYDRP PUMP",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 2,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 2,
    "processName": "Water Supply",
    "equipmentGroup": "5HP HYDRP PUMP",
    "equipmentName": "5HP HYDRP PUMP",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 3,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 3,
    "processName": "Water Supply",
    "equipmentGroup": "5HP SOFTENER MOTOR",
    "equipmentName": "5HP SOFTENER MOTOR",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 4,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 4,
    "processName": "Water Supply",
    "equipmentGroup": "5HP SOFTENER MOTOR",
    "equipmentName": "5HP SOFTENER MOTOR",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 5,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 5,
    "processName": "Fire Water Supply",
    "equipmentGroup": "60 HP Motor",
    "equipmentName": "60 HP Motor",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 6,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 6,
    "processName": "Water Supply",
    "equipmentGroup": "7.5 HP MOTOR",
    "equipmentName": "7.5 HP MOTOR",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 7,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 7,
    "processName": "Air Conditioner",
    "equipmentGroup": "2 TONN AC (ACCOUNTS)",
    "equipmentName": "2 TONN AC (ACCOUNTS)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 8,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 8,
    "processName": "Air Conditioner",
    "equipmentGroup": "1.5 TONN AC (HR)",
    "equipmentName": "1.5 TONN AC (HR)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 9,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 9,
    "processName": "Water Supply",
    "equipmentGroup": "0.75 HP SUMP MOTOR",
    "equipmentName": "0.75 HP SUMP MOTOR",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 10,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 10,
    "processName": "Air Conditioner",
    "equipmentGroup": "2 TONN AC (SERVER ROOM)",
    "equipmentName": "2 TONN AC (SERVER ROOM)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 11,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 11,
    "processName": "Air Conditioner",
    "equipmentGroup": "2 TONN AC (SERVER ROOM)",
    "equipmentName": "2 TONN AC (SERVER ROOM)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 12,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 12,
    "processName": "Laundry",
    "equipmentGroup": "LAUNDRY STEAM IRON TABLE (0.75 HP)",
    "equipmentName": "LAUNDRY STEAM IRON TABLE (0.75 HP)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 13,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 13,
    "processName": "Laundry",
    "equipmentGroup": "LAUNDRY STEAM IRON TABLE (0.75 HP)",
    "equipmentName": "LAUNDRY STEAM IRON TABLE (0.75 HP)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 14,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 14,
    "processName": "Laundry",
    "equipmentGroup": "LAUNDRY STEAM IRON TABLE (0.75 HP)",
    "equipmentName": "LAUNDRY STEAM IRON TABLE (0.75 HP)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 15,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 15,
    "processName": "Laundry",
    "equipmentGroup": "CLOTHES DRYER (24 KW & 2 HP)",
    "equipmentName": "CLOTHES DRYER (24 KW & 2 HP)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 16,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 16,
    "processName": "Laundry",
    "equipmentGroup": "CLOTHES DRYER (24 KW & 2 HP)",
    "equipmentName": "CLOTHES DRYER (24 KW & 2 HP)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 17,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 17,
    "processName": "Laundry",
    "equipmentGroup": "HYDRO EXTRACTOR (5 HP)",
    "equipmentName": "HYDRO EXTRACTOR (5 HP)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 18,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 18,
    "processName": "Laundry",
    "equipmentGroup": "HYDRO EXTRACTOR (5 HP)",
    "equipmentName": "HYDRO EXTRACTOR (5 HP)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 19,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 19,
    "processName": "Laundry",
    "equipmentGroup": "WASHING MACHINE (5 HP)",
    "equipmentName": "WASHING MACHINE (5 HP)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 20,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 20,
    "processName": "Laundry",
    "equipmentGroup": "WASHING MACHINE (5 HP)",
    "equipmentName": "WASHING MACHINE (5 HP)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 21,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 21,
    "processName": "Laundry",
    "equipmentGroup": "WASHING MACHINE (1 HP)",
    "equipmentName": "WASHING MACHINE (1 HP)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 22,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 22,
    "processName": "Laundry",
    "equipmentGroup": "CALENDAR IRONING MACHINE (3 HP)",
    "equipmentName": "CALENDAR IRONING MACHINE (3 HP)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 23,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 23,
    "processName": "Laundry",
    "equipmentGroup": "STEAM GENERATOR (100 KGS)",
    "equipmentName": "STEAM GENERATOR (100 KGS)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 24,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 24,
    "processName": "Exhaust",
    "equipmentGroup": "7.5 HP EXHAUST MOTOR",
    "equipmentName": "7.5 HP EXHAUST MOTOR",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 25,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 25,
    "processName": "Septic Tank",
    "equipmentGroup": "5 HP SUMP MOTOR (SEPTIC TANK)",
    "equipmentName": "5 HP SUMP MOTOR (SEPTIC TANK)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 26,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 26,
    "processName": "Air Conditioner",
    "equipmentGroup": "1.5 TONN AC (HKM)",
    "equipmentName": "1.5 TONN AC (HKM)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 27,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 27,
    "processName": "Air Conditioner",
    "equipmentGroup": "TWO DOOR FREEZER (2 TONN)",
    "equipmentName": "TWO DOOR FREEZER (2 TONN)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 28,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 28,
    "processName": "Air Conditioner",
    "equipmentGroup": "FOUR DOOR FREEZER (2 TONN)",
    "equipmentName": "FOUR DOOR FREEZER (2 TONN)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 29,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 29,
    "processName": "Air Conditioner",
    "equipmentGroup": "WALK IN COLD ROOM ( 5 TONN)",
    "equipmentName": "WALK IN COLD ROOM ( 5 TONN)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 30,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 30,
    "processName": "Air Conditioner",
    "equipmentGroup": "1.5 TONN AC (BUTCHERY)",
    "equipmentName": "1.5 TONN AC (BUTCHERY)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 31,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 31,
    "processName": "Air Conditioner",
    "equipmentGroup": "2 TONNE AC (HANGOUT 2)",
    "equipmentName": "2 TONNE AC (HANGOUT 2)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 32,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 32,
    "processName": "Air Conditioner",
    "equipmentGroup": "2.2 TONN AC (HANGOUT 1)",
    "equipmentName": "2.2 TONN AC (HANGOUT 1)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 33,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 33,
    "processName": "Air Conditioner",
    "equipmentGroup": "2.2 TONN AC (HANGOUT 1)",
    "equipmentName": "2.2 TONN AC (HANGOUT 1)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 34,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 34,
    "processName": "Air Conditioner",
    "equipmentGroup": "2.2 TONN AC (HANGOUT 1)",
    "equipmentName": "2.2 TONN AC (HANGOUT 1)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 35,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 35,
    "processName": "Water Supply",
    "equipmentGroup": "7.5 HP BOREWELL MOTOR",
    "equipmentName": "7.5 HP BOREWELL MOTOR",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 36,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 36,
    "processName": "Water Supply",
    "equipmentGroup": "5 HP BOREWELL MOTOR",
    "equipmentName": "5 HP BOREWELL MOTOR",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 37,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 37,
    "processName": "Air Conditioner",
    "equipmentGroup": "Blue Star Water Cooler",
    "equipmentName": "Blue Star Water Cooler",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 38,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 38,
    "processName": "Air Conditioner",
    "equipmentGroup": "Blue star Icecube Machine",
    "equipmentName": "Blue star Icecube Machine",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 39,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 39,
    "processName": "Air Conditioner",
    "equipmentGroup": "Walk-in Cold Room (3 Tonne)",
    "equipmentName": "Walk-in Cold Room (3 Tonne)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 40,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 40,
    "processName": "Dishwash",
    "equipmentGroup": "Dish Wash Machine",
    "equipmentName": "Dish Wash Machine",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 41,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 41,
    "processName": "Air Curtain",
    "equipmentGroup": "Air Curtains (1 HP)",
    "equipmentName": "Air Curtains (1 HP)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 42,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 42,
    "processName": "Air Curtain",
    "equipmentGroup": "Air Curtains (1 HP)",
    "equipmentName": "Air Curtains (1 HP)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 43,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 43,
    "processName": "Air Conditioner",
    "equipmentGroup": "Cafede A/C Indoor Unit",
    "equipmentName": "Cafede A/C Indoor Unit",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 44,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 44,
    "processName": "Air Conditioner",
    "equipmentGroup": "Cafede A/C Indoor Unit",
    "equipmentName": "Cafede A/C Indoor Unit",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 45,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 45,
    "processName": "Air Conditioner",
    "equipmentGroup": "Cafede A/C Indoor Unit",
    "equipmentName": "Cafede A/C Indoor Unit",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 46,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 46,
    "processName": "Air Conditioner",
    "equipmentGroup": "Lobby 1 A/C Indoor 16T",
    "equipmentName": "Lobby 1 A/C Indoor 16T",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 47,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 47,
    "processName": "Air Conditioner",
    "equipmentGroup": "Lobby 2 A/C Indoor 16T",
    "equipmentName": "Lobby 2 A/C Indoor 16T",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 48,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 48,
    "processName": "Air Conditioner",
    "equipmentGroup": "Back Office A/C Indoor 8T",
    "equipmentName": "Back Office A/C Indoor 8T",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 49,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 49,
    "processName": "Air Curtain",
    "equipmentGroup": "Lobby to Back Area Air Curtains",
    "equipmentName": "Lobby to Back Area Air Curtains",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 50,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 50,
    "processName": "Air Curtain",
    "equipmentGroup": "Lobby Entrance Air Curtains",
    "equipmentName": "Lobby Entrance Air Curtains",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 51,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 51,
    "processName": "Air Curtain",
    "equipmentGroup": "Lobby Entrance Air Curtains",
    "equipmentName": "Lobby Entrance Air Curtains",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 52,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 52,
    "processName": "Air Curtain",
    "equipmentGroup": "Lobby Entrance Air Curtains",
    "equipmentName": "Lobby Entrance Air Curtains",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 53,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 53,
    "processName": "Air Curtain",
    "equipmentGroup": "Lobby Entrance Air Curtains",
    "equipmentName": "Lobby Entrance Air Curtains",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 54,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 54,
    "processName": "Water Supply",
    "equipmentGroup": " Lobby Fountain Motor",
    "equipmentName": " Lobby Fountain Motor",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 55,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 55,
    "processName": "Water Supply",
    "equipmentGroup": "Fitness Center Sump Motor",
    "equipmentName": "Fitness Center Sump Motor",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 56,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 56,
    "processName": "Air Conditioner",
    "equipmentGroup": "Fitness Center A/C  8T",
    "equipmentName": "Fitness Center A/C  8T",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 57,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 57,
    "processName": "Exhaust",
    "equipmentGroup": "Kitch Exhaust (5 HP)",
    "equipmentName": "Kitch Exhaust (5 HP)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 58,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 58,
    "processName": "Exhaust",
    "equipmentGroup": "Fresh Air Motor",
    "equipmentName": "Fresh Air Motor",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 59,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 59,
    "processName": "Kitchen",
    "equipmentGroup": "Grinder (3 HP)",
    "equipmentName": "Grinder (3 HP)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 60,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 60,
    "processName": "Kitchen",
    "equipmentGroup": "Alu Machine (1 HP)",
    "equipmentName": "Alu Machine (1 HP)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 61,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 61,
    "processName": "Kitchen",
    "equipmentGroup": "Onion Cutting Machine (1 HP)",
    "equipmentName": "Onion Cutting Machine (1 HP)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 62,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 62,
    "processName": "Dishwash",
    "equipmentGroup": "Dish Wash Machine",
    "equipmentName": "Dish Wash Machine",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 63,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 63,
    "processName": "Exhaust",
    "equipmentGroup": "Kitchen Exhaust (3 HP)",
    "equipmentName": "Kitchen Exhaust (3 HP)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 64,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 64,
    "processName": "Water Supply",
    "equipmentGroup": "Water Cooler",
    "equipmentName": "Water Cooler",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 65,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 65,
    "processName": "Air Conditioner",
    "equipmentGroup": "Ice Cube Machine",
    "equipmentName": "Ice Cube Machine",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 66,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 66,
    "processName": "Air Conditioner",
    "equipmentGroup": "A/C Indoor Units 16T",
    "equipmentName": "A/C Indoor Units 16T",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 67,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 67,
    "processName": "Air Conditioner",
    "equipmentGroup": "A/C Indoor Units 8T",
    "equipmentName": "A/C Indoor Units 8T",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 68,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 68,
    "processName": "Air Conditioner",
    "equipmentGroup": "A/C Indoor Units 8T",
    "equipmentName": "A/C Indoor Units 8T",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 69,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 69,
    "processName": "Air Conditioner",
    "equipmentGroup": "Cocacola Fridge",
    "equipmentName": "Cocacola Fridge",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 70,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 70,
    "processName": "Air Conditioner",
    "equipmentGroup": "A/C Indoor Unit 8T",
    "equipmentName": "A/C Indoor Unit 8T",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 71,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 71,
    "processName": "Air Conditioner",
    "equipmentGroup": "A/C Indoor Unit 2T",
    "equipmentName": "A/C Indoor Unit 2T",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 72,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 72,
    "processName": "Air Conditioner",
    "equipmentGroup": "A/C Indoor Unit 2T",
    "equipmentName": "A/C Indoor Unit 2T",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 73,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 73,
    "processName": "Air Conditioner",
    "equipmentGroup": "A/C Indoor Unit 2T",
    "equipmentName": "A/C Indoor Unit 2T",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 74,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 74,
    "processName": "Exhaust",
    "equipmentGroup": "Gents Washroom Exhaust",
    "equipmentName": "Gents Washroom Exhaust",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 75,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 75,
    "processName": "Exhaust",
    "equipmentGroup": "Ladies Washroom Exhaust",
    "equipmentName": "Ladies Washroom Exhaust",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 76,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 76,
    "processName": "Water Supply",
    "equipmentGroup": "Swimming Pool Water Motor",
    "equipmentName": "Swimming Pool Water Motor",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 77,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 77,
    "processName": "Air Conditioner",
    "equipmentGroup": "Guest Lift A/C Unit (1.5 T)",
    "equipmentName": "Guest Lift A/C Unit (1.5 T)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 78,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 78,
    "processName": "Elevators",
    "equipmentGroup": "Guest Lift's",
    "equipmentName": "Guest Lift's",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 79,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 79,
    "processName": "Elevators",
    "equipmentGroup": "Guest Lift's",
    "equipmentName": "Guest Lift's",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 80,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 80,
    "processName": "Water Supply",
    "equipmentGroup": "Poolside Fountain Motor",
    "equipmentName": "Poolside Fountain Motor",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 81,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 81,
    "processName": "Heater",
    "equipmentGroup": "Big Tank Hot Water Heater's",
    "equipmentName": "Big Tank Hot Water Heater's",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 82,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 82,
    "processName": "Heater",
    "equipmentGroup": "Big Tank Hot Water Heater's",
    "equipmentName": "Big Tank Hot Water Heater's",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 83,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 83,
    "processName": "Heater",
    "equipmentGroup": "Big Tank Hot Water Heater's",
    "equipmentName": "Big Tank Hot Water Heater's",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 84,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 84,
    "processName": "Heater",
    "equipmentGroup": "Small Tank Hot Water Heater's",
    "equipmentName": "Small Tank Hot Water Heater's",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 85,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 85,
    "processName": "Heater",
    "equipmentGroup": "Small Tank Hot Water Heater's",
    "equipmentName": "Small Tank Hot Water Heater's",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 86,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 86,
    "processName": "Heater",
    "equipmentGroup": "Small Tank Hot Water Heater's",
    "equipmentName": "Small Tank Hot Water Heater's",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 87,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 87,
    "processName": "Water Supply",
    "equipmentGroup": "Cold Water Circulation Motor",
    "equipmentName": "Cold Water Circulation Motor",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 88,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 88,
    "processName": "Water Supply",
    "equipmentGroup": "Hot Water Circulation Motor",
    "equipmentName": "Hot Water Circulation Motor",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 89,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 89,
    "processName": "Water Supply",
    "equipmentGroup": "Solar Circulation Motor",
    "equipmentName": "Solar Circulation Motor",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 90,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 90,
    "processName": "Lighting",
    "equipmentGroup": "Shelton Big Letter's",
    "equipmentName": "Shelton Big Letter's",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 91,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 91,
    "processName": "Lighting",
    "equipmentGroup": "Shelton Big Letter's",
    "equipmentName": "Shelton Big Letter's",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 92,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 92,
    "processName": "Lighting",
    "equipmentGroup": "Shelton Small Letter's",
    "equipmentName": "Shelton Small Letter's",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 93,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 93,
    "processName": "Lighting",
    "equipmentGroup": "Shelton Telugu Letter's",
    "equipmentName": "Shelton Telugu Letter's",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 94,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 94,
    "processName": "Exhaust",
    "equipmentGroup": "Rooms Exhaust (3 HP)",
    "equipmentName": "Rooms Exhaust (3 HP)",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 95,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 95,
    "processName": "Septic Tank",
    "equipmentGroup": " S.T.P 2HP Blower",
    "equipmentName": " S.T.P 2HP Blower",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 96,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 96,
    "processName": "Septic Tank",
    "equipmentGroup": " S.T.P 5HP Cutter Pump",
    "equipmentName": " S.T.P 5HP Cutter Pump",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 97,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 97,
    "processName": "Septic Tank",
    "equipmentGroup": " S.T.P 5HP Cutter Pump",
    "equipmentName": " S.T.P 5HP Cutter Pump",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 98,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 98,
    "processName": "Septic Tank",
    "equipmentGroup": " S.T.P 1.5HP Sludge Pump",
    "equipmentName": " S.T.P 1.5HP Sludge Pump",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  },
  {
    "id": 99,
    "consumerType": "Commercial",
    "industryType": "Hotel",
    "serialNo": 99,
    "processName": "Septic Tank",
    "equipmentGroup": " S.T.P 1HP Filter Feed Pump",
    "equipmentName": " S.T.P 1HP Filter Feed Pump",
    "units": 1,
    "ratedLoad": null,
    "runningLoadKw": null,
    "operationType": "Continuous process",
    "criticalLoad": "High",
    "controlType": "Manual Control",
    "dailyOperatingHours": null,
    "peakRun": "Partial",
    "shiftable": "Yes",
    "maxShiftableLoadKw": 0.1,
    "maxShiftableDurationHours": 2,
    "managementApproval": "Yes",
    "remarks": "--"
  }
];
